/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projectexodus;


import static com.mycompany.projectexodus.FractionArithmetic.addAFraction;
import static com.mycompany.projectexodus.FractionArithmetic.additionOfFractions;
import static com.mycompany.projectexodus.FractionArithmetic.divisionOfFractions;
import static com.mycompany.projectexodus.FractionArithmetic.getIntroduction;
import static com.mycompany.projectexodus.FractionArithmetic.kb;
import static com.mycompany.projectexodus.FractionArithmetic.menu;
import static com.mycompany.projectexodus.FractionArithmetic.multiplicationOfFractions;
import static com.mycompany.projectexodus.FractionArithmetic.removeAFractions;
import static com.mycompany.projectexodus.FractionArithmetic.simplificationOfAFraction;
import static com.mycompany.projectexodus.FractionArithmetic.subtractionOfFractions;
import java.util.Scanner;
import java.util.Arrays;
import java.util.ArrayList;

/**
 *
 * @author Asus
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
  
        
    }

    
     public static void setNumber (int n ){
        
        number = n;
        
    }
     
     public static int getNumber (){
         
         
         return number;
     }
     
     
     public void setArrayOfFractions (ArrayList<Fraction> array ){
         
         arrayOfFractions = array;
         
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fraction Calculator");

        jButton2.setText("Manage Fractions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Addition of Fractions");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Multiplication of Fractions");

        jButton5.setText("Subtraction of Fractions");

        jButton6.setText("Division of Fractions");

        jButton7.setText("Simplify Fraction");

        jButton8.setText("Exit Program");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(8, 8, 8)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        AddAFraction AF = new AddAFraction();
        AF.passArrayToAddFraction(arrayOfFractions);
        
        AF.setVisible(true);
       
        dispose();
        

// TODO add your handling code here:
   
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        AdditionOfFractions panel1 = new AdditionOfFractions();
        panel1.setVisible(true);
        
        panel1.passArrayToAdditionOfFractions(arrayOfFractions);
      
        dispose();
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed
    public static Scanner kb = new Scanner(System.in);
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
        MainMenu Menu = new MainMenu();
        
        Fraction fractionArray [];
        int number = 0;
        int decision;
        int flag = 0;

        number = MainMenu.getNumber();
        fractionArray = new Fraction[number];

       

    }
    
    
    

    public static int menu (){

        int decision = 0;

        System.out.println(" ");
        System.out.println("MENU");
        System.out.println("1. ADD A FRACTION");
        System.out.println("2. REMOVE A FRACTION");
        System.out.println("3. ADDITION OF FRACTIONS");
        System.out.println("4. SUBTRACTION OF FRACTIONS");
        System.out.println("5. MULTIPLICATION OF FRACTIONS");
        System.out.println("6. DIVISION OF FRACTIONS");
        System.out.println("7. SIMPLIFY A FRACTION");
        System.out.println("8. EXIT PROGRAM");
        System.out.println(" ");
        System.out.print("Enter your choice: ");
        decision = Integer.parseInt(kb.nextLine());


        return decision;
    }

    public static Fraction[] addAFraction (int number, Fraction FractionArray []){

        int n = 0;
        int d = 0;

        for (int i = 0; i<number; i++) {

            System.out.print("Enter the numerator of the" + " " + (i+1) + " " + "number: ");
            n = Integer.parseInt(kb.nextLine());

            System.out.print("Enter the denominator of the" + " " + (i+1) + " " + "number: ");
            d = Integer.parseInt(kb.nextLine());


            FractionArray[i] = new Fraction(n,d);
        }

        return FractionArray;

    }

    public static Fraction[] removeAFractions (Fraction FractionArray[]){

        int pos = 0;

        System.out.println(" ");
        System.out.println(Arrays.toString(FractionArray));
        System.out.print("Enter the position of the fraction within the array: ");

        pos = Integer.parseInt(kb.nextLine());
        pos -= pos -1;

        for (int i = 0; i<FractionArray.length; i++){

            if (i == pos){

                FractionArray[i] = null;

                for (int j = i; j<FractionArray.length; j++){

                    if (j < FractionArray.length-1)

                        FractionArray[j] = FractionArray[j+1];




                }
            }
        }


        return FractionArray;
    }


    public static void additionOfFractions(Fraction arrayOfFractions[]){

        int pos1 = 0;
        int pos2 = 0;
        float result = 0;


        Fraction sum = new Fraction ();


        System.out.println(" ");
        System.out.println(Arrays.toString(arrayOfFractions));
        System.out.print("Enter the position of the first addend: ");
        pos1 = Integer.parseInt(kb.nextLine());

        System.out.print("Enter the position of the second addend: ");
        pos2 = Integer.parseInt(kb.nextLine());

        sum = arrayOfFractions[pos1-1].add(arrayOfFractions[pos2-1]);

        result = (float) sum.getNumerator()/sum.getDenominator();

        System.out.println("The sum is: " + sum.toString() + " " + "or " + result);



    }

    public static void subtractionOfFractions (Fraction arrayOfFractions []){

        int pos1 = 0;
        int pos2 = 0;
        float result = 0;

        Fraction difference = new Fraction ();

        System.out.println(" ");
        System.out.println(Arrays.toString(arrayOfFractions));

        System.out.print("Enter the Minuend: ");
        pos1 = Integer.parseInt(kb.nextLine());

        System.out.print("Enter the Subtrahend: ");
        pos2 = Integer.parseInt(kb.nextLine());

        difference = arrayOfFractions[pos1-1].subtract(arrayOfFractions[pos2-1]);


        result = (float) difference.getNumerator()/difference.getDenominator();

        System.out.println("The difference is: " + difference.toString() + " " + "or " + result);


    }

    public static void multiplicationOfFractions (Fraction arrayOfFractions []){

        int pos1 = 0;
        int pos2 = 0;
        float result = 0;

        Fraction product = new Fraction ();

        System.out.println(" ");
        System.out.println(Arrays.toString(arrayOfFractions));

        System.out.print("Enter the multiplier: ");
        pos1 = Integer.parseInt(kb.nextLine());

        System.out.print("Enter the multiplicand: ");
        pos2 = Integer.parseInt(kb.nextLine());

        product = arrayOfFractions[pos1-1].Multiply(arrayOfFractions[pos2-1]);

        result = (float) product.getNumerator()/product.getDenominator();

        System.out.println("The product is: " + product.toString() + " " + "or " + result);

    }

    public static void divisionOfFractions (Fraction arrayOfFractions[]){

        int pos1 = 0;
        int pos2 = 0;
        float result = 0;

        Fraction quotient = new Fraction();


        System.out.print(" ");
        System.out.println(Arrays.toString(arrayOfFractions));
        System.out.print("Enter the dividend: ");
        pos1 = Integer.parseInt(kb.nextLine());

        System.out.print("Enter the divisor: ");
        pos2 = Integer.parseInt(kb.nextLine());

        quotient = arrayOfFractions[pos1-1].divideBy(arrayOfFractions[pos2-1]);

        result = (float) quotient.getNumerator()/quotient.getDenominator();

        System.out.println("The quotient is: " + quotient.toString() +  " " + "or " + result);


    }

    public static Fraction[] simplificationOfAFraction (Fraction arrayOfFractions[]){

        int pos1 = 0;
        float decimal = 0;

        Fraction sFraction = new Fraction ();

        System.out.println(" ");
        System.out.print(Arrays.toString(arrayOfFractions));

        System.out.print("Enter the position of the fraction that will be simplified: ");
        pos1 = Integer.parseInt(kb.nextLine());

        sFraction = arrayOfFractions[pos1-1].reduce();

        arrayOfFractions[pos1-1] =  sFraction;



        return arrayOfFractions;
    }
    
    private static int number = 0;
    private static ArrayList<Fraction> arrayOfFractions;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
